#!/bin/bash
pwd; hostname; date
make LOCK_DEF=TAS1
make LOCK_DEF=TAS3
make LOCK_DEF=TAS4
make LOCK_DEF=TICKET1
make LOCK_DEF=TICKET3
make LOCK_DEF=TICKET4
make LOCK_DEF=MCS1
make LOCK_DEF=MCS3
make LOCK_DEF=MCS4
make LOCK_DEF=CLH1
make LOCK_DEF=CLH3
make LOCK_DEF=CLH4
make LOCK_DEF=ABQL1
make LOCK_DEF=ABQL3
make LOCK_DEF=ABQL4
export LD_LIBRARY_PATH=$PWD/lib
for i in {1..5}
	do
#	./bin/mcs1_lock_bench 24 >>results/mcs1_cpp.csv
#	./bin/mcs3_lock_bench 24 >>results/mcs3_cpp.csv
#	./bin/mcs4_lock_bench 24 >>results/mcs4_cpp.csv
#	./bin/tas1_lock_bench 24 >>results/tas1_cpp.csv
#	./bin/tas3_lock_bench 24 >>results/tas3_cpp.csv
#	./bin/tas4_lock_bench 24 >>results/tas4_cpp.csv
#	./bin/ticket1_lock_bench 24 >>results/ticket1_cpp.csv
#	./bin/ticket3_lock_bench 24 >>results/ticket3_cpp.csv
#	./bin/ticket4_lock_bench 24 >>results/ticket4_cpp.csv
        ./bin/clh1_lock_bench 24 >>results/clh1_cpp.csv
        ./bin/clh3_lock_bench 24 >>results/clh3_cpp.csv
        ./bin/clh4_lock_bench 24 >>results/clh4_cpp.csv
        ./bin/abql1_lock_bench 24 >>results/abql1_cpp.csv
        ./bin/abql3_lock_bench 24 >>results/abql3_cpp.csv
        ./bin/abql4_lock_bench 24 >>results/abql4_cpp.csv
	done
date
